/**
 * Golden parity tests for the German number formatting (#30).
 *
 * Every expected value was generated by executing the standalone editor's
 * final `formatValue` (reference file line 2629, the "simple display
 * formatting" patch) in Node — these tests are the port's parity contract.
 */
import { describe, expect, it } from 'vitest'
import { formatGermanEntry, formatValue, parseGermanEntry } from './number-format'

describe('formatValue', () => {
  it.each<[number, string]>([
    [NaN, '—'],
    [Infinity, '—'],
    [-Infinity, '—'],
  ])('non-finite %d → %j', (input, expected) => {
    expect(formatValue(input)).toBe(expected)
  })

  it.each<[number, string]>([
    [-0, '0'],
    // rounding collapses to zero: no '-0' may survive
    [-0.00001, '0'],
  ])('negative zero %d → %j', (input, expected) => {
    expect(formatValue(input)).toBe(expected)
  })

  describe('magnitude tiers', () => {
    it.each<[number, string]>([
      // |v| > 1000 → 0 decimals
      [1234567.891, '1 234 568'],
      [1000.4, '1 000'],
      [-56789, '-56 789'],
      [12345678, '12 345 678'],
      // 10 ≤ |v| ≤ 1000 → 2 decimals
      [1000, '1 000'],
      [999.999, '1 000'], // rounding crosses the grouping boundary
      [42.126, '42,13'],
      [10, '10'],
      [100.1, '100,1'],
      [-1234.5678, '-1 235'],
      // 1 ≤ |v| < 10 → 3 decimals
      [3.14159, '3,142'],
      [9.9999, '10'],
      [2.5, '2,5'],
      // |v| < 1 → 4 decimals (tier chosen from the ORIGINAL value)
      [0.5, '0,5'],
      [-0.5, '-0,5'],
      [0.1234, '0,1234'],
      [0.123456, '0,1235'],
      [0.9999999, '1'],
    ])('%d → %j', (input, expected) => {
      expect(formatValue(input)).toBe(expected)
    })
  })

  it.each<[number, string]>([
    [0, '0'],
    [7, '7'],
  ])('integer %d → %j', (input, expected) => {
    expect(formatValue(input)).toBe(expected)
  })
})

/**
 * Number ENTRY (#68) — not part of the parity port above. These are not
 * goldens from the reference editor: nothing there ever read a number a human
 * typed. The contract they pin is the one the student-facing controls need —
 * that the two directions are exact inverses, so a value survives being shown
 * and read back however many times a document is recomputed.
 */
describe('parseGermanEntry', () => {
  it.each<[string, string]>([
    ['1000', '1000'],
    ['7,5', '7.5'],
    ['7.5', '7.5'], // a point is already the plain form
    ['-0,25', '-0.25'],
    ['1 050', '1050'], // formatValue groups thousands with spaces
    ['1 234,56', '1234.56'],
    ['1.234,56', '1234.56'], // German grouping: the comma decides the decimals
    ['', ''],
  ])('%j → %j', (typed, expected) => {
    expect(parseGermanEntry(typed)).toBe(expected)
  })

  it('hands back text that is not a number exactly as it was typed', () => {
    expect(parseGermanEntry('keine Zahl')).toBe('keine Zahl')
    expect(parseGermanEntry('-')).toBe('-')
  })
})

describe('formatGermanEntry', () => {
  it.each<[string, string]>([
    ['1000', '1000'],
    ['7.5', '7,5'],
    ['-0.25', '-0,25'],
    ['0', '0'],
    ['keine Zahl', 'keine Zahl'],
  ])('%j → %j', (stored, expected) => {
    expect(formatGermanEntry(stored)).toBe(expected)
  })

  it('never groups and never rounds — unlike formatValue', () => {
    expect(formatGermanEntry('1234.5678')).toBe('1234,5678')
    expect(formatValue(1234.5678)).toBe('1 235')
  })
})

describe('the entry round trip', () => {
  it.each(['0', '1000', '7.5', '-0.25', '1234.5678', '0.000001'])(
    'survives show-then-read unchanged: %j',
    (stored) => {
      expect(parseGermanEntry(formatGermanEntry(stored))).toBe(stored)
    }
  )
})
